# Generated by Django 4.2.3 on 2023-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_miramar', '0005_alter_hotel_features_alter_room_room_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image_1',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image_2',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image_3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='no_of_guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_adults',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_children',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
