# Generated by Django 4.2.3 on 2023-07-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_miramar', '0007_alter_room_room_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_booked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
