# Generated by Django 4.2.3 on 2023-07-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_miramar', '0011_booking_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
